Repository upstage-org/limelight, pull requests merged in 2018-03, with the labels that each got.

#302 Issue#275 PR avatar distortion
  app/assets/javascripts/cable.js
  app/assets/javascripts/channels/avatars.coffee
Labels: avatars, bug

#308 Issue #273
  app/assets/javascripts/channels/avatars.coffee
Labels: avatars, bug

#306 R3-2018
  app/assets/javascripts/cable.js
  app/assets/javascripts/channels/avatars.coffee
  app/assets/javascripts/channels/theatre.coffee
Labels: release

#309 R3-2018 Branch Sync
  app/assets/javascripts/channels/avatars.coffee
Labels: sync

#311 Bump Ruby version to 2.5.0
  .ruby-version
Labels: enhancement

#313 Update Bundle
  Gemfile.lock
Labels: bug

#316 Issue #315
  Gemfile.lock
Labels: bug

#310 Issue#210
  app/assets/javascripts/sorttable.js
  app/models/avatar_tag.rb
  app/views/media/_table.html.erb
  app/views/tags/show.html.erb
Labels: bug, tags
