Repository upstage-org/limelight, pull requests merged in 2018-05, with the labels that each got.

#332 R6 2018
  Gemfile.lock
  app/assets/javascripts/channels/avatars.coffee
  app/assets/javascripts/channels/theatre.coffee
  app/controllers/messages_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/users_controller.rb
  app/models/user.rb
  app/views/announcements/_announcement.html.erb
  app/views/announcements/_form.html.erb
  app/views/announcements/show.html.erb
  app/views/messages/_message.html.erb
  app/views/sessions/new.html.erb
  app/views/stages/_form.html.erb
  app/views/subscriptions_mailer/make_announcement.html.erb
  app/views/theatre/_announcement.html.erb
  app/views/theatre/performance.html.erb
  app/views/users/_form.html.erb
  app/views/users/edit.html.erb
  app/views/users/index.html.erb
  app/views/users/show.html.erb
  db/migrate/20180417231338_change_user_nickname_to_username.rb
  db/migrate/20180417234942_force_lowercase_usernames.rb
  db/schema.rb
  db/seeds.rb
  spec/controllers/backdrops_controller_spec.rb
  spec/controllers/tags_controller_spec.rb
Labels: release

#330 Issue#271
  app/assets/javascripts/cable.js
Labels: avatars, backdrops, drawing

#340 Issue#307
  app/assets/javascripts/channels/avatars.coffee
  app/views/theatre/performance.html.erb
Labels: avatars, enhancement

#341 Issue#230
  app/views/stages/_form.html.erb
  app/views/stages/index.html.erb
  app/views/stages/show.html.erb
  app/views/users/index.html.erb
  app/views/users/show.html.erb
Labels: stages

#351 Address Travis build issue
  .travis.yml
Labels: bug

#349 Issue#190
  app/assets/javascripts/cable.js
  app/assets/javascripts/channels/avatars.coffee
  app/assets/javascripts/channels/theatre.coffee
  app/channels/avatar_channel.rb
  app/channels/drawing_channel.rb
Labels: enhancement
